---
# comments のルール
comments:
  active: true
  #
  # UndocumentedPublicClass
  #
  # 概要
  # - コメントがないパブリッククラスを禁止する
  #
  UndocumentedPublicClass:
    active: true  # (default: false)
  #
  # UndocumentedPublicClass
  #
  # 概要
  # - コメントがないパブリックな関数を禁止する
  #
  UndocumentedPublicFunction:
    active: true  # (default: false)
  #
  # UndocumentedPublicClass
  #
  # 概要
  # - コメントがないパブリックなプロパティを禁止する
  #
  UndocumentedPublicProperty:
    active: true  # (default: false)

# style のルール
style:
  active: true
  #
  # UnusedImports
  #
  # 概要
  # - 未使用の import を禁止する
  #
  UnusedImports:
    active: true  # (default: false)
# 潜在的なバグの検出
potential-bugs:
  active: true
  #
  # UnsafeCallOnNullableType
  #
  # 概要
  # - null 許容型に対しての安全でない呼び出しを禁止する
  UnsafeCallOnNullableType:
    active: true
    # 以下を除外対象に追加
    # - "**/presentation/model/**"
    #   - 理由: Validation のアノテーションで null チェックを実施し、セッターで `!!` を利用して non-null 型にするため。
    excludes: ["**/presentation/model/**", '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**']
